namespace T4Immutable {
  /// <summary>
  /// Access level (modifier) for constructors generated by T4Immutable.
  /// </summary>
  public enum ConstructorAccessLevel {
    Public,
    Protected,
    Internal,
    Private,
    ProtectedInternal
  }
}